# Generated by Django 4.0 on 2022-01-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DubberAPIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessToken', models.CharField(max_length=600)),
                ('refreshToken', models.CharField(max_length=600)),
                ('tokenExpiry', models.IntegerField()),
                ('expiryTime', models.DateTimeField()),
            ],
        ),
    ]
