# Generated by Django 4.0 on 2022-01-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dubberapitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='DubberCallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordingID', models.IntegerField()),
                ('callFrom', models.CharField(max_length=45)),
                ('callTo', models.CharField(max_length=45)),
                ('callType', models.CharField(max_length=45)),
                ('startTime', models.CharField(max_length=45)),
                ('startDate', models.DateField()),
                ('callDuration', models.IntegerField()),
                ('recordingChannel', models.CharField(max_length=45)),
                ('held', models.CharField(max_length=10)),
                ('interactionType', models.CharField(max_length=20)),
                ('dubPointID', models.CharField(max_length=45)),
                ('transcription', models.TextField()),
                ('sentiment', models.CharField(max_length=10)),
                ('analysed', models.CharField(max_length=10)),
                ('createdDate', models.DateTimeField()),
                ('anger', models.FloatField()),
                ('confident', models.FloatField()),
                ('fear', models.FloatField()),
                ('sadness', models.FloatField()),
                ('joy', models.FloatField()),
                ('analytical', models.FloatField()),
                ('tentative', models.FloatField()),
            ],
        ),
    ]
