# Generated by Django 4.0 on 2022-01-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dubbercallrecording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dubbercallrecording',
            name='id',
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='analysed',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='analytical',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='anger',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='callDuration',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='callFrom',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='callTo',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='callType',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='confident',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='createdDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='dubPointID',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='fear',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='held',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='interactionType',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='joy',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='recordingChannel',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='recordingID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='sadness',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='startDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='startTime',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='tentative',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='transcription',
            field=models.TextField(blank=True),
        ),
    ]
