# Generated by Django 4.0 on 2022-01-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_dubbercallrecording_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DubberLastInsertedRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beforeID', models.IntegerField()),
                ('createdDate', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='dubPointID',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='dubbercallrecording',
            name='recordingID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
