# Generated by Django 4.0 on 2022-01-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_dubberlastinsertedrecording_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DubberWebhookIDandSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.TextField(blank=True)),
                ('X_Hook_Secret', models.CharField(blank=True, max_length=250)),
                ('createdDate', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DubberWebhookNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(blank=True, max_length=100)),
                ('notificationURL', models.TextField(blank=True)),
                ('resourceURL', models.TextField(blank=True)),
                ('createdDate', models.DateTimeField(blank=True)),
            ],
        ),
    ]
