# Generated by Django 4.0 on 2022-01-10 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_dubberwebhookidandsecret_dubberwebhooknotifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dubberwebhookidandsecret',
            old_name='URL',
            new_name='notificationURL',
        ),
    ]
