# Generated by Django 4.0 on 2022-01-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_url_dubberwebhookidandsecret_notificationurl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DubberWebhookNotifications',
            new_name='DubberWebhookNotification',
        ),
    ]
