# Generated by Django 4.0 on 2022-01-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_dubbersmslogs_dubbersmsnotificationlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='dubbersmslogs',
            name='smsContent',
            field=models.TextField(blank=True),
        ),
    ]
