# Generated by Django 4.0 on 2022-01-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_dubberapitoken_expirytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubberapitoken',
            name='expiryTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
