# Generated by Django 4.0 on 2022-01-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_dubberapitoken_account_id_dubberapitoken_auth_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dubbersmslogs',
            name='smsType',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
